before_script:
  - apt-get update -qq && apt-get install -qq -y pandoc
  - pandoc --version

pages:
  stage: deploy
  only:
    - master
  script:
    - make
    - cp -r html public
  artifacts:
    paths:
      - public

